/**
 * Seed data for NCAA Men's Basketball teams
 * Maps ESPN team IDs to StatBroadcast GIDs
 * 
 * This data is automatically loaded from team-id-matches.json
 * which is generated by running:
 * 1. node scripts/scrape-statbroadcast-gids.js - Gets all StatBroadcast GIDs
 * 2. node scripts/match-espn-team-ids.js - Matches with ESPN team IDs
 * 
 * To add more teams:
 * - Re-run the scripts above to get updated matches
 * - Manually add any unmatched teams from data/team-id-unmatched.json
 */

const fs = require('fs');
const path = require('path');

// Load matched teams from JSON file
let teams = [];

try {
  // Path from src/database/seeds/ to data/ at project root
  const matchesPath = path.join(__dirname, '../../../data/team-id-matches.json');
  const matchedTeams = JSON.parse(fs.readFileSync(matchesPath, 'utf8'));
  
  // Convert matched teams to seed format
  teams = matchedTeams.map(match => ({
    teamId: match.teamId,
    statbroadcastGid: match.statbroadcastGid,
    teamName: match.teamName,
    sport: match.sport || 'mens-college-basketball',
    conference: null // Will be populated later if needed
  }));
  
  console.log(`Loaded ${teams.length} teams from team-id-matches.json`);
} catch (error) {
  console.error('Failed to load team matches:', error.message);
  console.error('Run: node scripts/match-espn-team-ids.js to generate team data');
  
  // Fallback to empty array - seeding will fail gracefully
  teams = [];
}

/**
 * Seed teams into database
 * @param {Object} teamRepository - TeamRepository instance
 */
async function seedTeams(teamRepository) {
  const logger = require('../../utils/logger');
  
  if (teams.length === 0) {
    logger.error('No teams to seed. Run: node scripts/match-espn-team-ids.js');
    return { total: 0, created: 0, updated: 0, failed: 0 };
  }
  
  logger.info('Starting team data seeding', { totalTeams: teams.length });
  
  let created = 0;
  let updated = 0;
  let failed = 0;
  
  for (const team of teams) {
    try {
      const existing = await teamRepository.getTeamByEspnId(team.teamId);
      
      await teamRepository.saveTeam(team);
      
      if (existing) {
        updated++;
        logger.debug('Updated team', { teamId: team.teamId, teamName: team.teamName });
      } else {
        created++;
        logger.debug('Created team', { teamId: team.teamId, teamName: team.teamName });
      }
    } catch (error) {
      failed++;
      logger.error('Failed to seed team', {
        teamId: team.teamId,
        teamName: team.teamName,
        error: error.message
      });
    }
  }
  
  logger.info('Team seeding completed', {
    total: teams.length,
    created,
    updated,
    failed
  });
  
  return { total: teams.length, created, updated, failed };
}

module.exports = {
  teams,
  seedTeams
};
